version: '2'

# docker build -t sports-betting-provider:latest -f Dockerfile .
services:
  server:
    image: sports-betting-provider:latest
    restart: always
    command: server
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongo:27017?retryWrites=true&writeConcern=majority
    ports:
      - 5000:5000
    depends_on:
      - mongo
  scraper:
    image: sports-scraper:latest
    restart: always
    environment:
      - 'MONGO_HOST=mongo'
      - 'INTERVAL_SECONDS=300'
      - 'USE_CACHE=t'
      - 'NUM_DAYS_PAST=7'
      - 'NUM_DAYS_FUTURE=21'
    volumes:
      - scraper:/opt/betting_data/
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    
volumes:
  mongo:
  scraper: